# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Thunkable # jekyll-seo-tag > Owners twitter username
author: Thunkable Extensions Community # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Thunkable
    - https://www.facebook.com/Thunkable
    - https://github.com/Thunkable
#    - https://www.linkedin.com/in/daviddarnes
#    - https://plus.google.com/+DavidDarnes

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "The AIX Directory" # The post list page content
    feature_text: |
      Welcome to the blog
    #images: 816, 668, 532, 445, 201, 48, 1-9  
    feature_image: "https://unsplash.it/1300/400?image=8"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Thunkable Extensions Directory" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
description: "This directory is developed and maintained by members of the Thunkable Community. We show you how to add extensions to your Thunkable apps and showcase some examples of extensions in action" # Site description and default description, also used in jekyll-seo-tag
url: "http://domhnallohanlon.com/thunkable_extensions/" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/domhnallohanlon/thunkable_extensions"
email: "hello@thunkable.com"
#disqus: "alembic-1"
avatarurl: "/assets/logo.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /thunkable_extensions/
  #Elements: /elements/
  Examples: /thunkable_extensions/blog/
  Categories: /thunkable_extensions/categories/
  Search: /thunkable_extensions/search/
  About: /thunkable_extensions/about/
  #Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by The Thunkable Community: http://community.thunkable.com
social_links:
  Twitter: https://twitter.com/thunkable
  GitHub: https://github.com/thunkable
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #Google+: https://plus.google.com/+DavidDarnes
  #link: https://darn.es

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ""
